# -- Enable/disable Redis
enabled: true

# -- Role of Redis in this chart
component: cache

# -- Override name
nameOverride: ""
# -- Override fullname
fullnameOverride: redis

image:
  # -- [Image repository](https://kubernetes.io/docs/concepts/containers/images/)
  repository: redis
  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart `appVersion`.
  tag: ""


# -- Create an additional LoadBalancer service for external redis access
loadBalancer:
  enabled: false

# -- [Image pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []

# -- Additional pod annotations
podAnnotations: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- [k8s: Security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
podSecurityContext: {}
  # fsGroup: 2000

# -- [k8s: Security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

persistence:
  # -- Enable/disable persistent data storage
  enabled: true
  # -- Redis [save](https://redis.io/commands/save/) args
  save: "60 1"
  # -- StorageClass to use, leave empty to use default StorageClass.
  storageClassName:
  # -- Mount path of the storage. Omit trailing `/` !
  accessModes:
    - ReadWriteOnce
  # -- Storage [capacity](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity)
  capacity: 4Gi
  # -- Annotations for PVCs
    # Set helm.sh/resource-policy: keep to avoid deletion of PVC on helm upgrade/uninstall
  annotations:
    # helm.sh/resource-policy: keep

# -- Number of replicas. Only used if `autoscaling.enabled = false`.
replicaCount: 1
autoscaling:
  # -- Enable/disable pod autoscaling, if disabled `replicaCount` is used to set number of pods.
  # Check requirements of [HorizontalPodAutoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).
  enabled: false
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Maximum number of replicas
  maxReplicas: 5
  # -- [HorizontalPodAutoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).
  targetCPUUtilizationPercentage:
  # -- [HorizontalPodAutoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).
  targetMemoryUtilizationPercentage:

service:
  # -- Type of service for http
  type: ClusterIP
  # -- Service port for http
  port: 6379

resources:
  limits:
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    cpu: 500m
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    memory: 1Gi
  requests:
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    cpu: 250m
    # -- [k8s: Resource management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
    memory: 256Mi

# -- [k8s: Assign pods to nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
nodeSelector: {}
# -- [k8S: Taints and tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
tolerations: []
# -- [k8s: Assign pods to nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
affinity: {}
