{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solr.fullname" . }}-init
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "solr.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
data:
  ckan_init_solr.sh: |
    #!/bin/bash

    set -e

    CKAN_SOLR_SCHEMA_URL="https://raw.githubusercontent.com/MarijaKnezevic/ckanext-scheme-sddi/refs/heads/main/ckanext/scheme_sddi/schema.xml"

    echo "Check whether managed schema exists for CKAN $CKAN_VERSION"
    if ! curl --output /dev/null --silent --head --fail "$CKAN_SOLR_SCHEMA_URL"; then
      echo "Can't find CKAN SOLR schema at URL: $CKAN_SOLR_SCHEMA_URL. Exiting..."
      exit 1
    fi

    echo "Check whether SOLR is initialized for CKAN"
    CORESDIR=/var/solr/data

    COREDIR="$CORESDIR/$CKAN_CORE_NAME"
    if [ -d "$COREDIR" ]; then
        echo "SOLR already initialized, skipping initialization"
    else
      echo "Initializing SOLR core $CKAN_CORE_NAME for CKAN $CKAN_VERSION"
      # init script for handling an empty /var/solr
      /opt/docker-solr/scripts/init-var-solr

      # Precreate CKAN core
      /opt/docker-solr/scripts/precreate-core $CKAN_CORE_NAME

      # Replace the managed schema with CKANs schema
      echo "Adding CKAN managed schema"
      curl $CKAN_SOLR_SCHEMA_URL -o /var/solr/data/$CKAN_CORE_NAME/conf/managed-schema -s

      echo "SOLR initialized"
    fi
{{- end -}}
