{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-sct-session
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
stringData:
  CKAN___SEKRET_KEY: {{ .Values.session.secretKey | default (randAlphaNum 20) | quote }}
  CKAN___SESSION_TYPE: {{ .Values.session.type | default "cookie" | quote }}
  CKAN___SESSION_PERMANENT: {{ .Values.session.permanent | default "True" | quote }}
  CKAN___PERMANENT_SESSION_LIFETIME: {{ .Values.session.permanentSessionLifetime | default "3600" | quote }}
  CKAN___SESSION_REFRESH_EACH_REQUEST: {{ .Values.session.refreshEachRequest | default "False" | quote }}
  CKAN___SESSION_COOKIE_NAME: {{ .Values.session.cookie.name | default "ckan" | quote }}
  CKAN___SESSION_COOKIE_DOMAIN: {{ .Values.session.cookie.domain | default "" | quote }}
  CKAN___SESSION_COOKIE_PATH: {{ .Values.session.cookie.path | default "" | quote }}
  CKAN___SESSION_COOKIE_HTTPONLY: {{ .Values.session.cookie.httpOnly | default "True" | quote }}
  CKAN___SESSION_COOKIE_SECURE: {{ .Values.session.cookie.secure | default "False" | quote }}
  CKAN___SESSION_COOKIE_SAMESITE: {{ .Values.session.cookie.sameSite | default "Lax" | quote }}
{{- end -}}
